name = "My Beautiful Pack"
author = "RozeFound"
version = "0.0.5"
description = "Cool pack, isn't it?"

# only github supported

[[Resource]]
name = "BCLib"
filename = "bclib-0.4.0.jar"
url = "https://github.com/paulevsGitch/BCLib/releases/download/0.4.0/bclib-0.4.0.jar"
