name = "My Beautiful Pack"
author = "RozeFound"
version = "0.0.6"
description = "Cool pack, isn't it?"

[[Resource]]
name = "BCLib"
filename = "bclib-0.4.0.jar"
url = "https://github.com/paulevsGitch/BCLib/releases/download/0.4.0/bclib-0.4.0.jar"

[[Resource]]
name = "Complementary Shaders"
filename = "ComplementaryShaders_v4.1.zip"
url = "https://edge.forgecdn.net/files/3391/516/ComplementaryShaders_v4.1.zip"
