name = "My Beautiful Pack" # modpack name, recommended
author = "RozeFound" # modpack author, recommended
version = "0.0.9" # modpack version, required, will be prompted if not specified
description = "Cool pack, isn't it?" # optional

# Available url domains:
#
#    cdn.modrinth.com
#    gitlab.com
#    github.com
#    raw.githubusercontent.com

# Forbidden url domains:
#
#    edge.forgecdn.net
#    media.forgecdn.net
#
# Still can be used, but will raise an error if --exclude-forbidden specified

[[Resource]]
# resource name, for  fabric mods it's `name` field in fabric.mod.json
# For forge mods, it's `description` in pack.mcmeta
name = "BCLib"
filename = "bclib-0.4.0.jar" 
url = "https://github.com/paulevsGitch/BCLib/releases/download/0.4.0/bclib-0.4.0.jar"

[[Resource]]
# For other files it's filename without extension, but for convinience you can specify what you want here
# Because to find the resource, it checks resource name OR filename
# But specifying both, name and filename is highly recommended for propper indentifying
name = "Complementary Shaders"
filename = "ComplementaryShaders_v4.1.zip"
url = "https://edge.forgecdn.net/files/3391/516/ComplementaryShaders_v4.1.zip"

# field action can contain "override", "remove", or "ignore"
[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip" 
action = "override" # force move resource to overrides

[[Resource]]
name = "Farsight Mod"
filename = "farsight.fabric-1.18-1.9.jar"
action = "remove" # deletes resource from pack completely

[[Resource]]
name = "YOSBR"
action = "ignore" # Shut up the warning
