[tool.poetry]
name = "mc-modpack-converter"
version = "0.1.0"
description = ""
authors = ["RozeFound"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
murmurhash2 = "^0.2.9"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
